export const niveis = [
	['DIA', 'BOLA', 'DADO', 'VIDA', 'AVE'],
	['NOITE', 'LUGARES', 'GARÇOM', 'OFICINA', 'VIADUTO'],
	['ENERGIZADO', 'HELICÓPTERO', 'CONJUNTIVITE', 'GARFIELD', 'VENEZIANA'],
	['PARALELEPÍPEDO', 'ESPETACULARIZADO', 'BALAÚSTRE', 'CORNUCÓPIA', 'OTORRINOLARINGOLOGISTA'],
	[
		'VOCÊ JÁ TOMOU BANHO HOJE?',
		'ESSA GENTE INVENTA CADA COISA',
		'TUA MÃE SABE QUE USAS A CORTINA DELA?',
		'EM TERRA DE ALEIJADO, QUALQUER CHUTE É VOADORA',
		'POR QUE SE PREOCUPAR COM O AMANHÃ SE ELE ACABA DEPOIS DE AMANHÃ?'
	]
];
